### ISSUE TITLE
Ember test hangs if there is a specific dependency chain.

### ISSUE THREAD

**Issue by robert-j-webb** [salsify/ember-css-modules#83] opened 2017-10-12 17:02 UTC
I'm using ember-css-module: 0.7.3, ember-cli: 2.15.1, node: 8.4.0

This bug only happens with ember test, and it only happens when I have this specific dependency chain: 

file-0.css
```css
:global .foo{
  color: red;
}
```

file-1.css

```css
.foo {
  composes: foo from global;
  color: green;
}
```

file-2.css

```css
.foo {
  composes: foo from 'nlroot/**/styles.css';
  color: green;
}
```

I wasn't able to reproduce this in a test repo. It may be a combination of plugins and build interacting with each other.

**Comment by dfreeman** [comment] 2017-11-10 20:26
Hi @robert-j-webb — sorry you're running into this issue. I don't know of anything off the top of my head that would lead to hangs based on dependency chains like this, and if you're not able to reproduce it outside your specific repo, I'm not sure there's much I can do to help you debug it 😞 

If you do manage to figure out what the bad interaction is, though, I'm happy to help try and get to the bottom of it!

**Comment by dfreeman** [comment] 2018-02-06 23:20
@robert-j-webb I'm going to go ahead and close this out, since there isn't anything we can do here without a reproduction. If you do manage to reproduce it, please let me know!

**Closed by dfreeman** 2018-02-06 23:20 UTC
Labels: need submitter response
