### ISSUE TITLE
Support co-located components

### ISSUE THREAD

**Issue by lolmaus** [salsify/ember-css-modules#151] opened 2019-09-03 07:55 UTC
RFC: https://github.com/emberjs/rfcs/blob/master/text/0481-component-templates-co-location.md

This is already available in Octane.

At the same time, Octane currently does not support pods: https://github.com/emberjs/ember.js/issues/18350

On the bleeding edge, we're stuck with classically separated component files. :finnadie:

**Comment by dfreeman** [comment] 2019-09-28 15:52
Work is underway (and actually has been for a bit) to support this, but unfortunately for now it's blocked on https://github.com/ember-cli/ember-cli-htmlbars/issues/307

**Comment by chancancode** [comment] 2019-09-30 05:32
The upstream issue is fixed in ember-cli-htmlbars v4.0.2!

**Comment by dfreeman** [comment] 2019-10-02 19:48
There's now **experimental** support for co-located components in `1.3.0-beta.1`. If you have the opportunity to give it a try and report back what works or doesn't, that would be great!

**Comment by NullVoxPopuli** [comment] 2019-12-21 12:53
I'm switching from ember-component-css (in-progress). One "gotchya" I came across was that I had to remove ember-cli-postcss to get my app.css to not be "lost": https://discordapp.com/channels/480462759797063690/486013244667068436/657923983840247839

**Comment by lolmaus** [comment] 2020-01-24 08:21
> There's now experimental support for co-located components in 1.3.0-beta.1. If you have the opportunity to give it a try and report back what works or doesn't, that would be great!

Works for us! 👍

**Comment by luxferresum** [comment] 2020-02-09 05:14
Same for us. Would love to see this in stable.

**Comment by gvocale** [comment] 2020-02-14 20:32
I get infinite page refresh an components repeated multiple times when doing something like:
```
// text/index.hbs
<span local-class="text">
  {{yield}}
</span>
```

```
// text/index.ts
import Component from '@glimmer/component';

export default class Text extends Component {}
```

```
// text/styles.module.scss
.text {
  color: red;
}
```

**Comment by lolmaus** [comment] 2020-02-14 20:47
@gvocale Does it stop flipping if you remove `ember-css-modules` from `package.json`?

**Comment by gvocale** [comment] 2020-02-15 06:23
@lolmaus I tried to reproduce on a freshly created ember-quickstart project and works correctly. I have to check again in case I made some other mistakes in the big app where it wasn't working.

**Comment by lolmaus** [comment] 2020-02-15 07:23
@gvocale Infinite rendering is Glimmer glitch. Check for syntax and passed arguments, e. g. empty actions, misused helpers, etc.

**Comment by gvocale** [comment] 2020-02-15 18:27
@lolmaus interesting! Nice to know. I sometimes run into glimmer rendering issues when passing wrong arguments, without any error mention in console. Hopefully with future versions more useful errors will be added.

**Comment by dfreeman** [comment] 2020-11-11 14:55
Co-located component templates are now supported since 1.3.0, so I'm going to close this out 🙂

**Closed by dfreeman** 2020-11-11 14:55 UTC
Labels: enhancement
