### ISSUE TITLE
Not working with other css tools (Less)

### ISSUE THREAD

**Issue by antulik** [salsify/ember-css-modules#28] opened 2016-05-19 05:36 UTC
after `ember-css-modules` is installed ember build fails as `ember-cli-less` could not find the required files.

```
The Broccoli Plugin: [LessCompiler] failed with:
Error: File not found: /app/styles/app.less
in any of the following include paths:
  /Users/anton/work/opensight-ember/tmp/less_compiler-input_base_path-UwlBJIdU.tmp/0
    at Object.findFileSync (/Users/anton/work/opensight-ember/node_modules/include-path-searcher/index.js:12:9)
    at LessCompiler.build (/Users/anton/work/opensight-ember/node_modules/broccoli-less-single/index.js:49:35)
    at /Users/anton/work/opensight-ember/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/anton/work/opensight-ember/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/anton/work/opensight-ember/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/anton/work/opensight-ember/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/anton/work/opensight-ember/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

The broccoli plugin was instantiated at:
    at LessCompiler.Plugin (/Users/anton/work/opensight-ember/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at LessCompiler.CachingWriter [as constructor] (/Users/anton/work/opensight-ember/node_modules/broccoli-caching-writer/index.js:21:10)
    at new LessCompiler (/Users/anton/work/opensight-ember/node_modules/broccoli-less-single/index.js:21:17)
    at /Users/anton/work/opensight-ember/node_modules/ember-cli-less/index.js:28:12
    at Array.map (native)
    at LESSPlugin.toTree (/Users/anton/work/opensight-ember/node_modules/ember-cli-less/index.js:24:34)
    at /Users/anton/work/opensight-ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/anton/work/opensight-ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/Users/anton/work/opensight-ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
```

I've tried not to use `app.less` but rather different filename, but still no luck.

I'd like to be able to use both (less and css-modules) at the same time, even if they isolated from each other

**Comment by dfreeman** [comment] 2016-05-19 15:35
The fact that `app.less` gets lost definitely looks like a bug on this end. Assuming that's something simple (and I suspect it is), you should be able to get `ember-css-modules` and `ember-cli-less` working pretty smoothly in isolation from one another once that's fixed.

Actually using the two in concert is going to be a harder problem (partially discussed in #4). In particular with Less, the `@value foo: bar;` syntax conflicts with Less's `@foo: bar;` variables, which will likely limit what's possible.

Regardless, losing the `.less` file is something we should be able to fix—I'll see if I can track that down before the next release goes out.

**Comment by ynnoj** [comment] 2016-05-24 13:50
I'm encountering the same issue, but when using `ember-cli-postcss`.

`Error: File not found: /app/styles/app.css
in any of the following include paths:
  /Users/J/git/trainer/trainer-app/tmp/postcss_compiler-input_base_path-4bqR9kkN.tmp/0
    at Object.findFileSync (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/include-path-searcher/index.js:12:9)
    at PostcssCompiler.build (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/index.js:32:42)
    at /Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:415:9)
    at process._tickCallback (node.js:344:13)

The broccoli plugin was instantiated at: 
    at PostcssCompiler.Plugin (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at PostcssCompiler.CachingWriter (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/node_modules/broccoli-caching-writer/index.js:21:10)
    at new PostcssCompiler (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/node_modules/broccoli-postcss-single/index.js:18:17)
    at /Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/index.js:29:12
    at Array.map (native)
    at PostcssPlugin.toTree (/Users/J/git/trainer/trainer-app/node_modules/ember-cli-postcss/index.js:26:34)
    at /Users/J/git/trainer/trainer-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
    at EmberApp.styles (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1262:28)
    at EmberApp.toArray (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1565:10)
    at EmberApp.toTree (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/Users/J/git/trainer/trainer-app/ember-cli-build.js:43:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/J/git/trainer/trainer-app/node_modules/ember-cli/lib/models/builder.js:89:10)`

**Comment by dfreeman** [comment] 2016-05-24 13:53
@ynnoj You shouldn't have any need for `ember-cli-postcss` with this—you can pass PostCSS plugins directly to this addon to be executed as part of the modules pipeline. Is there something specific you're looking to do with `ember-cli-postcss` that you can't accomplish that way?

**Comment by ynnoj** [comment] 2016-05-24 14:34
@dfreeman Awesome! I did not realise that. I'll adjust the project build setup and see how it works out.

Thanks!

**Comment by jasonmit** [comment] 2016-06-03 01:26
I haven't really gotten to the bottom of this yet, but it looks like the `toTree` function within ember-cli-less never gets called when ember-css-modules is added to the problem.

I'll report back if I can figure out why...

**Comment by jasonmit** [comment] 2016-06-03 01:42
I think I found the issue, PR incoming soon.

**Comment by dfreeman** [comment] 2016-06-03 16:05
@jasonmit thanks for investigating — I got as far as the dropped `inputNode`, but came to the same conclusion around it still being difficult to get multiple CSS preprocessors to live nicely together.

I have a couple other ideas I'll try playing with when I next have some time to devote to squashing bugs here.

**Comment by jasonmit** [comment] 2016-06-05 05:54
Yeah, the thing about merging the tree I found that it will write the original styles tree, in it's entirety, to the dist (not just the concatted app.css).  This required then to do some postProcessTree filtering to make sure that folder structure gets filtered out.

The core of the issue is that ember-cli doesn't support really two preprocessors on the same tree-type without hacks in place, such as:

https://github.com/jasonmit/______ember-css-example/blob/master/lib/postcss-addon/index.js#L13-L21

Have you explored moving this logic to a `treeForStyles` hook instead of registering a preprocessor for the type `js` this way other addons might be able to mutate that tree before [ember-css-modules does](https://github.com/jasonmit/______ember-css-example/blob/master/package.json#L50).  I haven't yet explored this, just hacked around it for now.

This is really impressive work, great addon.

**Comment by dfreeman** [comment] 2016-06-08 15:31
@jasonmit The story of this addon is mostly one of plumbing trees between places that Ember CLI doesn't really expect them to go 😉 .

@antulik I _think_ I've got a reasonable fix on [this branch](https://github.com/salsify/ember-css-modules/compare/coexistence), with [a demo app](https://github.com/dfreeman/--css-modules-coexistence/commit/c778c37e6f71d7ecce0d8d620a47d52eb286249a) making use of it. It allows you to specify an `intermediateOutputPath` for the concatenated modules so that your preprocessor of choice can import that and then do whatever else it wants in order to produce the final output.

That branch still needs documentation and testing, but can you take a look and see if it seems like it'll solve your problem?

**Comment by dfreeman** [comment] 2016-07-12 04:01
This is now possible in 0.4.0, which was just released — see the README for details.

**Closed by dfreeman** 2016-07-12 04:01 UTC
Labels: bug
