### ISSUE TITLE
Doesn't work with angle bracket polyfill

### ISSUE THREAD

**Issue by musaffa** [salsify/ember-css-modules#104] opened 2018-07-31 14:42 UTC
If I add [ember-angle-bracket-invocation-polyfill](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill) to an ember project, ECM's local-class declarations just get removed from the final template output.

**Comment by dfreeman** [comment] 2018-07-31 17:51
I took a quick pass at this and was unable to reproduce. Can you provide a repo that demonstrates the issue?

**Comment by musaffa** [comment] 2018-07-31 18:37
Here's a sample repo reproducing the issue: https://github.com/musaffa/angle-brackets

**Comment by dfreeman** [comment] 2018-07-31 19:34
Aha, I see — it looks like `ember-angle-bracket-invocation-polyfill` monkey patches some bits of the component lookup process, and that's interfering with how ECM attempts to resolve styles. It also appears to have a weird impact on Ember Inspector (which relies on the same underlying `_debugContainerKey`):

![image](https://user-images.githubusercontent.com/108688/43482074-ae620f54-94d5-11e8-8b9d-28e490d37549.png)

The good news (and the reason I wasn't able to reproduce this) is that if you add a `component.js` file, that just does `export default Component.extend({});`, it should solve both problems:

![image](https://user-images.githubusercontent.com/108688/43482112-bfcd4948-94d5-11e8-9774-3a40cfa80dcc.png)

**Comment by musaffa** [comment] 2018-07-31 19:49
It's probably related to rwjblue/ember-angle-bracket-invocation-polyfill#22.

**Comment by dfreeman** [comment] 2018-08-01 14:33
Could well be. I also forgot to mention that our approach to resolving styles has been overhauled on master to work better with things like template-only components, so I would expect it not to have this problem even if you don't have a `component.js`.

**Comment by musaffa** [comment] 2018-08-01 17:25
This is really great. Waiting for the new release. Btw, you can change the label attached to this issue.

**Comment by dfreeman** [comment] 2018-09-07 04:11
This should be resolved in 1.0.0-beta.1 (just released 🎉)

**Closed by dfreeman** 2018-09-07 04:11 UTC
