### ISSUE TITLE
Build fails when add styles.css to existing component

### ISSUE THREAD

**Issue by b-ponomarenko** [salsify/ember-css-modules#43] opened 2016-09-01 16:21 UTC
When I create new component, like `ember g component cc-component`, and then add styles.css to component folder build fails and I has this message:
`The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: EEXIST: file already exists, symlink '/Users/bponomarenko/Desktop/css-modules-app/app/components/uu-ii/component.js' -> '/Users/bponomarenko/Desktop/css-modules-app/tmp/broccoli_merge_trees-output_path-L5fMoPvn.tmp/css-modules-app/components/uu-ii/component.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at symlink (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/node_modules/symlink-or-copy/index.js:55:5)
    at BroccoliMergeTrees.<anonymous> (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/index.js:137:16)
    at Array.forEach (native)
    at BroccoliMergeTrees._applyPatch (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/index.js:114:9)
    at BroccoliMergeTrees.build (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/index.js:101:10)
    at /Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1036:16)`

`The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/node_modules/broccoli-merge-trees/index.js:42:10)
    at ModulesPreprocessor.toTree (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-css-modules/lib/modules-preprocessor.js:50:16)
    at /Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessJs (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at EmberApp.appAndDependencies (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1071:25)
    at EmberApp.javascript (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1199:34)
    at EmberApp.toArray (/Users/bponomarenko/Desktop/css-modules-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1604:10)`

**Comment by dfreeman** [comment] 2016-09-02 17:55
This looks like it _could_ be a bug in `broccoli-merge-trees`, but I'm not positive. I should have some time to dig in further over the weekend and see if I can find the culprit.

**Comment by dfreeman** [comment] 2016-09-07 16:13
@b-ponomarenko Confirmed this as an upstream bug: https://github.com/broccolijs/broccoli-merge-trees/issues/50

**Comment by nightire** [comment] 2016-10-15 13:10
@b-ponomarenko FYI, before this bug got resolved, you can create a placeholder directory includes all files you needed, e.g. `component.js` `template.hbs` and `styles.css`. Every time you need a new component, just copy this folder and rename it, just a trick to get around.

**Comment by dfreeman** [comment] 2016-11-17 17:54
A fix for this just landed in `broccoli-merge-trees@1.1.5` 🎉 . That's a floating dependency of ember-cli, so `rm -rf node_modules && npm install` should get you the latest version across the board.

I'm going to go ahead and close this out, but as always feel free to reopen or file a fresh issue if you're still not seeing the behavior you expect.

**Closed by dfreeman** 2016-11-17 17:54 UTC
Labels: bug, upstream-issue
